"""Generate TypeScript schema types from the composed FastAPI OpenAPI schema."""
import json
import os
from pathlib import Path
import tempfile

def convert(schema):
    if '$ref' in schema:return schema['$ref'].split('/')[-1]
    if 'enum' in schema:return ' | '.join(json.dumps(v) for v in schema['enum'])
    if 'const' in schema:return json.dumps(schema['const'])
    variants=schema.get('anyOf') or schema.get('oneOf')
    if variants:return '('+' | '.join(convert(s) for s in variants)+')'
    kind=schema.get('type')
    if kind=='null':return 'null'
    if kind in {'integer','number'}:return 'number'
    if kind=='boolean':return 'boolean'
    if kind=='string':return 'string'
    if kind=='array':return '('+convert(schema.get('items',{}))+')[]'
    if kind=='object' or 'properties' in schema:
        if not schema.get('properties'):return 'Record<string,'+convert(schema.get('additionalProperties',{}))+'>' if isinstance(schema.get('additionalProperties'),dict) else 'Record<string,unknown>'
        required=set(schema.get('required',[]))
        return '{'+';'.join(json.dumps(k)+('' if k in required else '?')+':'+convert(v) for k,v in schema['properties'].items())+'}'
    return 'unknown'

def main():
    root=Path(__file__).resolve().parents[2]
    with tempfile.TemporaryDirectory(prefix='openlearn-schema-') as directory:
        os.environ.update(FORMA_DB_PATH=str(Path(directory)/'schema.sqlite'),AI_TUTOR_ENV='development',AI_TUTOR_DEV_IDENTITY='true',OPENLEARN_MIGRATE_ON_START='true')
        from backend.app.main import app,store
        try:schema=app.openapi()
        finally:store.close()
    target=root/'mobile/src/generated/api.ts'
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text('// Generated by backend/scripts/generate_mobile_contracts.py; do not edit.\n'+'\n'.join('export type '+name+' = '+convert(value)+';' for name,value in sorted(schema['components']['schemas'].items()))+'\n',encoding='utf-8')
    print('Generated mobile API schemas:',len(schema['components']['schemas']))

if __name__=='__main__':main()
