"use client";
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, BookOpen, Check, LoaderCircle, LogOut, Mail, ShieldCheck, X } from 'lucide-react';
import { supabaseAccount } from '@/lib/supabase-account';
import { accountManager, signOut } from '@/lib/account-session';
import styles from './auth-flow.module.css';

export type AuthMode = 'login' | 'signup';
function GoogleMark() { return <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.8 12.2c0-.7-.1-1.4-.2-2.1H12v4h5.5a4.7 4.7 0 0 1-2 3v2.6h3.3c1.9-1.8 3-4.4 3-7.5Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.8-2.4l-3.3-2.6c-.9.6-2.1 1-3.5 1-2.7 0-5-1.8-5.8-4.3H2.8v2.7A10.2 10.2 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.2 13.7a6 6 0 0 1 0-3.4V7.6H2.8a10 10 0 0 0 0 8.8l3.4-2.7Z"/><path fill="#EA4335" d="M12 6c1.5 0 2.9.5 3.9 1.5l2.9-2.8A9.9 9.9 0 0 0 12 2a10.2 10.2 0 0 0-9.2 5.6l3.4 2.7C7 7.8 9.3 6 12 6Z"/></svg>; }
export function AuthForm({mode, onModeChange}:{mode:AuthMode;onModeChange?:(mode:AuthMode)=>void}) {
  const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState<'email'|'google'|null>(null),[error,setError]=useState(''),[cooldown,setCooldown]=useState(0);
  useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>clearTimeout(timer);},[cooldown]);
  async function sendEmail(event?:FormEvent){event?.preventDefault();setBusy('email');setError('');try{const client=supabaseAccount();if(!client)throw new Error('Sign-in is temporarily unavailable. Please try again.');const {error}=await client.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:mode==='signup',emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error)throw error;setSent(true);setCooldown(60);}catch(cause){setError(cause instanceof Error?cause.message:'We could not send your link. Please try again.');}finally{setBusy(null);}}
  async function google(){setBusy('google');setError('');try{const client=supabaseAccount();if(!client)throw new Error('Sign-in is temporarily unavailable. Please try again.');const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error)throw error;}catch(cause){setError(cause instanceof Error?cause.message:'Google sign-in could not start. Please try again.');setBusy(null);}}
  const other=mode==='login'?'signup':'login';
  return <div className={styles.form}>
    <div className={styles.symbol}>{sent?<Mail size={25}/>:<BookOpen size={25}/>}</div>
    <h1>{sent?'Check your inbox':mode==='signup'?'Your next idea starts here':'Welcome back'}</h1>
    <p className={styles.description}>{sent?<>We sent a secure sign-in link to <strong>{email.trim()}</strong>. Open it in this browser to continue.</>:mode==='signup'?'Create your free Open Learn account. Keep your chats, notes, and learning together.':'Log in to pick up your conversations, notes, and learning where you left off.'}</p>
    {sent?<div className={styles.sent}><p><Check size={17}/> No password to remember</p><button className={styles.primary} disabled={!!busy||cooldown>0} onClick={()=>void sendEmail()}>{busy?<LoaderCircle className={styles.spin} size={18}/>:null}{cooldown?`Resend link in ${cooldown}s`:'Resend sign-in link'}</button><button className={styles.textButton} disabled={!!busy} onClick={()=>{setSent(false);setError('');}}>Use a different email</button><small>Can’t find it? Check your spam folder.</small></div>:<>
      <button className={styles.google} disabled={!!busy} onClick={()=>void google()}>{busy==='google'?<LoaderCircle className={styles.spin} size={20}/>:<GoogleMark/>}{busy==='google'?'Opening Google…':'Continue with Google'}</button>
      <div className={styles.divider}><span/>or continue with email<span/></div>
      <form onSubmit={event=>void sendEmail(event)}><label htmlFor={`auth-email-${mode}`}>Email address</label><input id={`auth-email-${mode}`} type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254} value={email} onChange={event=>setEmail(event.target.value)} disabled={!!busy} aria-describedby={error?'auth-error':undefined}/><button className={styles.primary} disabled={!!busy}>{busy==='email'?<LoaderCircle className={styles.spin} size={18}/>:null}{busy==='email'?'Sending your link…':mode==='signup'?'Create free account':'Continue with email'}{!busy?<ArrowRight size={18}/>:null}</button></form>
      <p className={styles.secure}><ShieldCheck size={14}/> A secure email link. No password needed.</p>
    </>}
    {error?<p id="auth-error" className={styles.error} role="alert">{error}</p>:null}
    {!sent?<p className={styles.switch}>{mode==='login'?'New to Open Learn?':'Already have an account?'}{' '}{onModeChange?<button onClick={()=>{setError('');onModeChange(other);}}>{mode==='login'?'Sign up for free':'Log in'}</button>:<Link href={mode==='login'?'/auth/sign-up':'/auth/sign-in'}>{mode==='login'?'Sign up for free':'Log in'}</Link>}</p>:null}
  </div>;
}
export function AuthScreen({mode}:{mode:AuthMode}) {return <main className={styles.screen}><Link href="/" className={styles.brand}><BookOpen size={23}/> Open Learn</Link><div className={styles.background} aria-hidden="true"><span>A space for your curiosity.</span><p>Ask a question. Find a connection. Make it yours.</p></div><section className={styles.card} aria-label={mode==='signup'?'Create an account':'Log in'}><Link href="/" className={styles.close} aria-label="Return to Open Learn"><X size={20}/></Link><AuthForm mode={mode}/></section><p className={styles.footer}>Your learning, in one place.</p></main>;}
export function SignOutScreen({signedOut=false}:{signedOut?:boolean}){const [busy,setBusy]=useState(false),[done]=useState(signedOut),[error,setError]=useState('');async function logout(){setBusy(true);setError('');try{await signOut();window.location.replace('/auth/signed-out');}catch(cause){setError(cause instanceof Error?cause.message:'Sign-out failed. Please try again.');}finally{setBusy(false);}}return <main className={styles.screen}><Link href="/" className={styles.brand}><BookOpen size={23}/> Open Learn</Link><section className={styles.card}><div className={styles.form}><div className={styles.symbol}>{done?<Check size={25}/>:<LogOut size={25}/>}</div><h1>{done?'You’re signed out':'Sign out of Open Learn?'}</h1><p className={styles.description}>{done?'Your chats and notes are saved to your account. Log in whenever you’re ready to continue.':'Your saved chats and notes stay in your account. This signs you out on this browser.'}</p>{done?<><Link className={styles.primary} href="/auth/sign-in">Log back in <ArrowRight size={18}/></Link><Link className={styles.textButton} href="/">Return to Open Learn</Link></>:<><button className={styles.primary} onClick={()=>void logout()} disabled={busy}>{busy?<LoaderCircle className={styles.spin} size={18}/>:<LogOut size={18}/>} {busy?'Signing out…':'Sign out'}</button><Link className={styles.textButton} href="/"><ArrowLeft size={16}/> Stay signed in</Link></>}{error?<p className={styles.error} role="alert">{error}</p>:null}</div></section></main>;}

export function AuthCallbackScreen(){const started=useRef(false);const [error,setError]=useState('');useEffect(()=>{if(started.current)return;started.current=true;const client=accountManager();if(!client){setError('Sign-in is temporarily unavailable. Please try again.');return;}void client.signinRedirectCallback().then(()=>window.location.replace('/')).catch(()=>setError('This sign-in link could not be completed. It may have expired or already been used.'));},[]);return <main className={styles.screen}><Link href="/" className={styles.brand}><BookOpen size={23}/> Open Learn</Link><section className={styles.card}><div className={styles.form}><div className={styles.symbol}>{error?<Mail size={25}/>:<LoaderCircle className={styles.spin} size={25}/>}</div><h1>{error?'Let’s try that again':'Opening your study space'}</h1><p className={styles.description} role="status">{error||'Finishing your secure sign-in. You’ll be ready in a moment.'}</p>{error?<Link className={styles.primary} href="/auth/sign-in">Back to login <ArrowRight size={18}/></Link>:null}</div></section></main>;}
