"use client";
import { useCallback, useEffect, useState } from 'react';
import {openWorkspaceFlashcards} from '@/lib/workspace-events';
import { request } from '@/lib/api';
import { Button } from './ui/button';
import { useBuddies } from './buddies';
import {RoutineControls} from './routine-controls';
import {ReminderDeliveryStatus} from './reminder-delivery-status';
type Reminder={kind:'academic'|'chat'|'routine';url?:string;lastError?:string;id:string;dueAt:number;status:string;title:string;courseId:string|null;buddyId:string};
export function BuddyReminders({initialReminderId,onCourse}:{initialReminderId?:string|null;onCourse?:(id:string)=>void}){const [flashcardNotices,setFlashcardNotices]=useState<{id:string;title:string;body:string;status:string}[]>([]);const [items,setItems]=useState<Reminder[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const {snapshot,refresh}=useBuddies();const [filter,setFilter]=useState('');const [selected,setSelected]=useState(initialReminderId||'');const [busyId,setBusyId]=useState('');
 async function action(item:Reminder,verb:'cancel'|'snooze'){setBusyId(item.id);try{await request(`/v1/reminders/${item.id}/${verb}`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:verb==='snooze'?JSON.stringify({minutes:60}):undefined});await load();}catch(e){setError(e instanceof Error?e.message:'Could not update reminder.');}finally{setBusyId('');}}
 const load=useCallback(async()=>{setLoading(true);try{const result=await request<{reminders:Reminder[]}>('/v1/buddies/reminders');setItems(result.reminders);const cards=await request<{notifications:{id:string;title:string;body:string;status:string}[]}>('/v1/flashcard-notifications');setFlashcardNotices(cards.notifications);setError('');await request('/v1/buddies/reminders/read',{method:'POST',body:JSON.stringify({reminderIds:result.reminders.filter(item=>!initialReminderId||item.id===initialReminderId).slice(0,1000).map(item=>item.id)})});await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not load reminders.');}finally{setLoading(false);}},[refresh,initialReminderId]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);const poll=setInterval(()=>void load(),30000);return()=>{clearTimeout(timer);clearInterval(poll);};},[load]);
 return <section className="buddy-home"><h2>Reminders</h2><p>Shared across your Buddies and chats.</p><RoutineControls/><label>Companion <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All Buddies</option>{snapshot?.profiles.map(buddy=><option key={buddy.id} value={buddy.id}>{buddy.name}</option>)}</select></label>{selected?<Button variant="ghost" onClick={()=>setSelected('')}>Show all reminders</Button>:null}{loading?<p role="status">Loading reminders…</p>:null}{error?<p role="alert">{error}<Button onClick={()=>void load()}>Retry</Button></p>:null}{!loading&&!error&&!items.length?<p>No reminders yet. Course reminder settings are available in your courses.</p>:null}{flashcardNotices.map(notice=><article className="buddy-preview" key={notice.id}><strong>{notice.title}</strong><p>{notice.body}</p><Button onClick={()=>openWorkspaceFlashcards({view:'library'})}>Review flashcards</Button><Button variant="ghost" onClick={()=>void request(`/v1/assistant/notifications/${notice.id}/ack`,{method:'POST'}).then(()=>void load())}>Mark read</Button></article>)}{items.filter(item=>(!filter||item.buddyId===filter)&&(!selected||item.id===selected)).map(item=><article key={item.id} className="buddy-preview"><small>{snapshot?.profiles.find(p=>p.id===item.buddyId)?.name||'Buddy'}</small><strong>{item.title}</strong><p>{new Date(item.dueAt*1000).toLocaleString()} · {item.kind} · {item.status}</p><ReminderDeliveryStatus id={item.id}/>{item.lastError?<p role="status">This reminder needs attention.</p>:null}{item.url&&item.status==='delivered'?<Button asChild variant="outline"><a href={item.url}>Open activity</a></Button>:null}{['pending','delivered'].includes(item.status)?<Button variant="outline" disabled={busyId===item.id} onClick={()=>void action(item,'snooze')}>Snooze 1 hour</Button>:null}{item.status==='pending'?<Button variant="ghost" disabled={busyId===item.id} onClick={()=>void action(item,'cancel')}>{item.kind==='routine'?'Cancel routine':'Cancel'}</Button>:null}{item.courseId&&onCourse?<Button variant="outline" onClick={()=>onCourse(item.courseId!)}>Open course</Button>:null}</article>)}</section>;
}
