"use client";
import type { CourseSummary } from '@/lib/api';
import { Button } from './ui/button';
import { useEffect, useState } from 'react';
import { request } from '@/lib/api';
import { useBuddies } from './buddies';
type Event={id:string;courseId:string;title:string;kind:string;when:{kind:string;value:string}};
export function BuddyToday({courses,due,onCourse,onReview,onAdd,onReminders,onClass,onPrep,scheduleOnly=false}:{scheduleOnly?:boolean;courses:CourseSummary[];due:number;onCourse:(id:string)=>void;onReview:()=>void;onAdd:()=>void;onReminders:()=>void;onClass?:(id:string)=>void;onPrep?:(id:string,title:string)=>void}) {
  const {snapshot}=useBuddies();const [events,setEvents]=useState<Event[]>([]),[error,setError]=useState('');
  useEffect(()=>{let live=true;void request<{events:Event[]}>('/v1/buddies/today').then(result=>{if(live)setEvents(result.events);}).catch(()=>{if(live)setError('Your schedule could not load. Open a course to check upcoming work.');});return()=>{live=false;};},[]);
  return <section className="buddy-home" aria-label="Today"><h2>Your study space</h2>{error?<p role="status">{error}</p>:null}<div className="buddy-today">{events.map(event=>{const buddy=snapshot?.profiles.find(p=>p.id===(snapshot.courses[event.courseId]||snapshot.defaultBuddyId));return <article className="buddy-event" key={event.id}><strong>{event.title}</strong><small>{courses.find(c=>c.id===event.courseId)?.name} · {buddy?.name} · {event.when.kind==='instant'?new Date(event.when.value).toLocaleString():event.when.value}</small><Button size="sm" variant="ghost" onClick={()=>onCourse(event.courseId)}>Open course</Button>{event.kind==='class'&&onClass?<Button size="sm" onClick={()=>onClass(event.courseId)}>Start class</Button>:onPrep?<Button size="sm" onClick={()=>onPrep(event.courseId,event.title)}>Quick prep</Button>:null}</article>;})}{!events.length&&!scheduleOnly?(courses.length?<button onClick={()=>onCourse(courses[0].id)}><strong>{courses[0].name}</strong><small>Add your schedule, prepare, or start a class</small></button>:<button onClick={onAdd}><strong>Add your first course</strong><small>Give your Buddy some study context</small></button>):null}{!scheduleOnly&&due>0?<button onClick={onReview}><strong>{due} concepts due for review</strong><small>Pick up where you left off</small></button>:null}{!scheduleOnly?<button onClick={onReminders}><strong>Reminders</strong><small>See upcoming reminders saved to your account</small></button>:null}</div>{scheduleOnly&&!events.length&&!error?<p>No upcoming activities. Add a schedule in a course to plan your next session.</p>:null}{!scheduleOnly?<Button variant="ghost" onClick={onAdd}>Add a course</Button>:null}</section>;
}
