'use client';
import {useEffect,useState} from 'react';
import {apiBaseUrl,request} from '@/lib/api';
import {Button} from '@/components/ui/button';
type Connection={id:string;origin:string;status:string;lastSuccessfulSync?:number};
export function CanvasConnection({courseId}:{courseId:string}) {
 const [origin,setOrigin]=useState(''),[course,setCourse]=useState(''),[config,setConfig]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[items,setItems]=useState<Connection[]>([]);
 async function refresh(){setItems(await request('/v1/canvas/connections'));}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 async function pair(){setBusy(true);setError('');try{let deviceId=localStorage.getItem('open-learn-canvas-device');if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem('open-learn-canvas-device',deviceId);}const courses={[course]:courseId};const result=await request<{id:string;grant:string;deviceId:string;authToken:string}>('/v1/canvas/pair',{method:'POST',body:JSON.stringify({origin,deviceId,courses})});const desktop=(window as Window & {formaDesktop?:{apiToken?:string}}).formaDesktop;setConfig(JSON.stringify({backend:apiBaseUrl(),origin,deviceId:result.deviceId,courses,connectionId:result.id,grant:result.grant,authToken:result.authToken,desktopToken:desktop?.apiToken},null,2));await refresh();}catch(e){setError(e instanceof Error?e.message:'Pairing failed.');}finally{setBusy(false);}}
 return <details className="course-folder-section"><summary>Connect your local Canvas browser</summary><p>Install the Open Learn Canvas Reader extension, then approve one institution and course. Keep Canvas signed in in your browser. Reads run while this device and browser are available.</p><label>Institution origin<input placeholder="https://canvas.example.edu" value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>Canvas course ID<input value={course} onChange={e=>setCourse(e.target.value)}/></label><Button disabled={busy||!course||!origin} onClick={()=>void pair()}>Create pairing</Button>{config?<label>Paste into the extension; this configuration contains a session credential<textarea readOnly rows={8} value={config}/></label>:null}{error?<p role="alert">{error}</p>:null}<ul>{items.map(item=><li key={item.id}>{item.origin} · {item.status} · {item.lastSuccessfulSync?new Date(item.lastSuccessfulSync*1000).toLocaleString():'No complete sync yet'}<Button variant="ghost" onClick={()=>void request(`/v1/canvas/connections/${item.id}`,{method:'DELETE'}).then(refresh).catch(e=>setError(e.message))}>Disconnect</Button></li>)}</ul></details>;
}
