"use client";
import {useEffect,useState} from 'react';
import {apiBaseUrl,request} from '@/lib/api';
import {authenticatedFetch} from '@/lib/account-session';
import type {Deck,FlashcardContent} from '@/lib/flashcards-client';
import {Button} from './ui/button';
import styles from './flashcards.module.css';

export function FlashcardImage({image,revealed=false}:{image:FlashcardContent['image'];revealed?:boolean}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(!image)return;let active=true,local='';setUrl('');const headers=new Headers();const desktop=(window as Window&{formaDesktop?:{apiToken?:string}}).formaDesktop?.apiToken;if(desktop)headers.set('X-Forma-Desktop-Token',desktop);void authenticatedFetch(`${apiBaseUrl()}/v1/flashcard-images/${encodeURIComponent(image.versionId)}`,{headers}).then(async response=>{if(!response.ok)throw Error('This image is unavailable. Check its source access.');const blob=await response.blob();if(active){local=URL.createObjectURL(blob);setUrl(local);}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;if(local)URL.revokeObjectURL(local)};},[image?.versionId]);
 if(!image)return null;
 return <figure>{url?<div style={{position:'relative',width:'100%'}}><img src={url} alt={image.altText} style={{width:'100%',display:'block'}}/>{!revealed?image.masks.map((mask,i)=><span key={i} aria-hidden="true" style={{position:'absolute',left:`${mask.x*100}%`,top:`${mask.y*100}%`,width:`${mask.width*100}%`,height:`${mask.height*100}%`,background:'var(--foreground,#222)',border:'2px solid var(--background,#fff)'}}/>):null}</div>:<p role={error?'alert':'status'}>{error||'Loading private image…'}</p>}<figcaption>{image.altText}{!revealed&&image.masks.length?' · Label regions concealed':''}</figcaption></figure>;
}

export function NewFlashcard({deck,onCreate}:{deck:Deck;onCreate:(content:FlashcardContent)=>Promise<void>}){
 const [open,setOpen]=useState(false),[type,setType]=useState<FlashcardContent['type']>('qa'),[prompt,setPrompt]=useState(''),[answer,setAnswer]=useState(''),[quote,setQuote]=useState(''),[sourceId,setSourceId]=useState(deck.coverage.sources[0]?.id||''),[assets,setAssets]=useState<{versionId:string;title:string;mediaType:string}[]>([]),[asset,setAsset]=useState(''),[alt,setAlt]=useState(''),[rights,setRights]=useState(false),[mask,setMask]=useState({x:10,y:10,width:30,height:10}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const visual=type==='image_label'||type==='image_occlusion';
 useEffect(()=>{if(!open||!visual)return;let active=true;void request<{materials:{versionId:string;title:string;mediaType:string}[]}>(`/v1/materials${deck.courseId?'?course_id='+encodeURIComponent(deck.courseId):''}`).then(value=>{if(active)setAssets(value.materials.filter(m=>['image/png','image/jpeg','image/webp'].includes(m.mediaType)));}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;};},[open,visual,deck.courseId]);
 async function save(){setBusy(true);setError('');try{await onCreate({type,prompt,answer,explanation:'',sourceIds:[sourceId],supportQuote:quote,conceptIds:[],image:visual?{versionId:asset,altText:alt,rightsConfirmed:rights,masks:type==='image_occlusion'?[{x:mask.x/100,y:mask.y/100,width:mask.width/100,height:mask.height/100}]:[]}:null});setOpen(false);setPrompt('');setAnswer('');setQuote('');}catch(e){setError(e instanceof Error?e.message:'Could not add card.');}finally{setBusy(false);}}
 return <div><Button variant="outline" onClick={()=>setOpen(v=>!v)}>Add a card</Button>{open?<section className={styles.card}><label>Card style<select value={type} onChange={e=>setType(e.target.value as FlashcardContent['type'])}><option value="qa">Question/answer</option><option value="cloze">Cloze deletion</option><option value="image_label">Image label</option><option value="image_occlusion">Image occlusion</option></select></label><label>Prompt<textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>Answer<textarea value={answer} onChange={e=>setAnswer(e.target.value)}/></label><label>Supporting source<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{deck.coverage.sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>Supporting passage<textarea value={quote} onChange={e=>setQuote(e.target.value)}/></label>{visual?<><label>Private image source<select value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Choose an uploaded image</option>{assets.map(a=><option value={a.versionId} key={a.versionId}>{a.title}</option>)}</select></label>{!assets.length?<p>Upload a PNG, JPEG or WebP under Materials first.</p>:null}<label>Alternative description (without revealing the answer)<textarea value={alt} onChange={e=>setAlt(e.target.value)}/></label><label className={styles.selected}><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>I have permission to use this image for my study cards</label>{type==='image_occlusion'?<><p>Concealed label rectangle, as percentages of the image. The rectangle must fit within its bounds.</p><div className={styles.toolbar}>{(['x','y','width','height'] as const).map(key=><label key={key}>{key}<input type="number" min={key==='width'||key==='height'?1:0} max={100} value={mask[key]} onChange={e=>setMask(m=>({...m,[key]:Number(e.target.value)}))}/></label>)}</div></>:null}{asset&&alt?<FlashcardImage image={{versionId:asset,altText:alt,rightsConfirmed:rights,masks:type==='image_occlusion'?[{x:mask.x/100,y:mask.y/100,width:mask.width/100,height:mask.height/100}]:[]}}/>:null}</>:null}<Button disabled={busy||!sourceId||!prompt.trim()||!answer.trim()||!quote.trim()||visual&&(!asset||!alt.trim()||!rights)} onClick={()=>void save()}>Save as draft</Button>{error?<p role="alert">{error}</p>:null}</section>:null}</div>;
}
