'use client';
import {useEffect,useState} from 'react';
import {request} from '@/lib/api';
import {Button} from './ui/button';
type Preferences={timezone:string;quietStart:number;quietEnd:number;channels:string[];emailOptIn:boolean};
export function ReminderPreferences(){
 const [value,setValue]=useState<Preferences|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{let live=true;void request<Preferences>('/v1/reminder-preferences').then(v=>{if(live)setValue(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 async function save(){if(!value)return;setBusy(true);setSaved(false);try{await request('/v1/reminder-preferences',{method:'PUT',body:JSON.stringify(value)});setError('');setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Could not save preferences.');}finally{setBusy(false);}}
 return <section aria-label="Chat reminder preferences"><h3>Chat reminders and routines</h3><p>One-time reminders use the exact time you request. Routines respect quiet hours.</p>{value?<div className="notification-preferences"><label>Timezone<input value={value.timezone} onChange={e=>{setSaved(false);setValue({...value,timezone:e.target.value});}} placeholder="America/Los_Angeles"/></label><label>Quiet hours start<input type="number" min={0} max={23} value={value.quietStart} onChange={e=>setValue({...value,quietStart:Number(e.target.value)})}/></label><label>Quiet hours end<input type="number" min={0} max={23} value={value.quietEnd} onChange={e=>setValue({...value,quietEnd:Number(e.target.value)})}/></label>{['push','desktop','expo'].map(channel=><label key={channel}><input type="checkbox" checked={value.channels.includes(channel)} onChange={e=>setValue({...value,channels:e.target.checked?[...value.channels,channel]:value.channels.filter(c=>c!==channel)})}/>{channel==='push'?'Browser push':channel==='expo'?'Mobile push':'Desktop alerts'}</label>)}<label><input type="checkbox" checked={value.emailOptIn} onChange={e=>setValue({...value,emailOptIn:e.target.checked,channels:e.target.checked?[...value.channels.filter(c=>c!=='email'),'email']:value.channels.filter(c=>c!=='email')})}/>Email notifications</label><Button disabled={busy} onClick={()=>void save()}>Save reminder preferences</Button>{saved?<p role="status">Preferences saved.</p>:null}</div>:null}{error?<p role="alert">{error}</p>:null}</section>;
}
