"use client";
import {useEffect,useState} from 'react';
import {useAllowance,usagePercent,refreshAllowance,usageActivityLabel} from '@/lib/usage-allowance';
import {request} from '@/lib/api';
import './usage-allowance.css';
type Activity={id:string;root_id:string;period_id:string;component:string;microcredits:number;held_micro?:number;grant_micro:number;status?:'pending'|'in_progress'|'settled';source:string;created_at?:number|string;components?:{component:string;microcredits:number;held_micro?:number;source:string}[]};
type Adjustment={id:string;component:string;kind:string;microcredits:number;created_at:number|string};
function activityTime(value:number|string){const time=typeof value==='number'?value*1000:Date.parse(value);return Number.isFinite(time)?new Date(time).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Recent';}
export function UsageAllowance({compact=false,active=false}:{compact?:boolean;active?:boolean}){
 const{snapshot,error}=useAllowance(active);const[activity,setActivity]=useState<Activity[]>([]),[adjustments,setAdjustments]=useState<Adjustment[]>([]);
 useEffect(()=>{if(compact||!snapshot)return;let cancelled=false;void request<{items:Activity[];adjustments?:Adjustment[]}>('/v1/usage/activity').then(r=>{if(!cancelled){setActivity(Array.isArray(r.items)?r.items:[]);setAdjustments(Array.isArray(r.adjustments)?r.adjustments:[]);}}).catch(()=>{});return()=>{cancelled=true;};},[compact,snapshot]);
 const p=snapshot?usagePercent(snapshot):null;
 if(!p||!snapshot)return compact?null:<section className="usage-allowance"><p>{error||'Loading your allowance…'}</p><button onClick={()=>void refreshAllowance()}>Retry</button></section>;
 if(snapshot.testUnlimited&&snapshot.availability==='available')return compact?null:<section className="usage-allowance"><strong>Test account · allowance limits disabled</strong><p>Usage is still recorded. Platform spending and provider safeguards apply.</p></section>;
 const blocked=snapshot.availability!=='available';if(compact&&p.used<80&&!blocked)return null;
 const reset=snapshot.resetsAt?new Date(snapshot.resetsAt*1000).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):null;
 const notice=snapshot.reasonCode==='usage_window_exhausted'?(p.held>0?'Remaining allowance is reserved for ongoing work.':`Your allowance refreshes at ${reset}. Your work is saved.`):blocked?'AI work is temporarily unavailable while service capacity or previous usage is checked.':p.used>=95?'You are close to your AI allowance limit.':p.used>=80?'Most of your AI allowance has been used.':'';
 return <section className={`usage-allowance${compact?' usage-allowance-compact':''}`} aria-label="AI allowance"><strong>Usage · {p.label} used</strong>{!compact?<><div className="usage-allowance-track" role="meter" aria-label="AI allowance used" aria-valuemin={0} aria-valuemax={100} aria-valuenow={p.used} aria-valuetext={`${p.label} used, ${Math.round(p.held)}% reserved`}><span style={{width:`${p.used}%`}}/><i style={{width:`${p.held}%`}}/></div><p>{Math.round(p.held)}% reserved · {Math.round(p.available)}% available</p><p>Chat, voice and agent tasks share this allowance. Longer responses and tools use more.</p></>:null}<small>{reset?`Refreshes at ${reset}`:'Your five-hour window starts when you use AI'}</small>{notice?<p role="status">{notice}</p>:null}{error?<small>{error}</small>:null}{!compact&&(activity.length||adjustments.length)?<details><summary>Recent usage</summary>{activity.map(item=><p key={`${item.id}:${item.period_id}`}>{item.components?.length?item.components.map(part=>part.component).join(' · '):item.component} · {usageActivityLabel({used:item.microcredits,held:item.held_micro||0,grant:item.grant_micro,status:item.status})}{item.source==='estimated'?' · estimated':''}{item.created_at?` · ${activityTime(item.created_at)}`:''}</p>)}{adjustments.map(item=>{const percent=item.microcredits*100/snapshot.grantedMicrocredits;const amount=`${percent>0?'+':''}${percent.toFixed(1).replace(/\.0$/,'')}%`;return <p key={`adjustment:${item.id}`}>Usage adjustment · {item.component} · {item.kind.replace(/[_-]+/g,' ')} · {amount} · {activityTime(item.created_at)}</p>;})}</details>:null}</section>;
}
