'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Plus, Repeat2 } from 'lucide-react';
import { request, type CourseSummary } from '@/lib/api';
import { ACCOUNT_CHANGED } from '@/lib/account-session';
import { CALENDAR_CHANGED, wallInstant, dateKey, type StudentCalendar } from '@/lib/calendar-client';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '../ui/dialog';
import styles from './calendar.module.css';

type Routine = { id: string; revision: number; active: boolean; message: string; timezone: string; schedule: { type: 'cron' | 'rrule'; cron?: string; rrule?: string; startsAt?: string }; calendarPresentation?: string; calendarId?: string; durationMinutes?: number; courseId?: string; sessionId?: string; channels?: string[]; actions?: unknown[]; quietStart?: number; quietEnd?: number; maxFires?: number; expiresAt?: number | null; condition?: unknown; catchupMinutes?: number; buddyId?: string };

export function CalendarRoutines({ calendars, courses, zone, onStart, compact = false }: { calendars: StudentCalendar[]; courses: CourseSummary[]; zone: string; onStart: (course: string, title: string) => void; compact?: boolean }) {
  const [items, setItems] = useState<Routine[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState('');
  const [editing, setEditing] = useState<Routine | 'new' | null>(null);
  const epoch = useRef(0);
  const load = useCallback(async () => { const version = ++epoch.current; try { const result = await request<{ routines: Routine[] }>('/v1/reminders'); if (epoch.current === version) { setItems(result.routines); setError(''); } } catch (cause) { if (epoch.current === version) setError(cause instanceof Error ? cause.message : 'Routines could not load.'); } finally { if (epoch.current === version) setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(),0); const reset = () => { epoch.current++; setItems([]); setEditing(null); setError(''); void load(); }; window.addEventListener(ACCOUNT_CHANGED, reset); return () => { window.clearTimeout(timer); epoch.current++; window.removeEventListener(ACCOUNT_CHANGED, reset); }; }, [load]);
  async function control(item: Routine, action: string) {
    if (action === 'delete' && !window.confirm(`Delete the recurring routine “${item.message}”? Its history will be preserved.`)) return;
    setBusy(item.id); setError('');
    try { await request(`/v1/reminder-routines/${encodeURIComponent(item.id)}`, { method: 'PATCH', body: JSON.stringify({ expectedRevision: item.revision, action }) }); await load(); window.dispatchEvent(new Event(CALENDAR_CHANGED)); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not update routine.'); }
    finally { setBusy(''); }
  }
  return <div className={`${styles.routines} ${compact ? styles.routinesCompact : ''}`}><div className={styles.toolbar}><div><h2>Your routines</h2>{!compact ? <p>Make time for study, or let Buddy prepare something on a schedule.</p> : null}</div><Button size={compact ? 'sm' : 'default'} onClick={() => setEditing('new')}><Plus size={16}/>{compact ? 'Add' : 'Add routine'}</Button></div>{loading ? <p role="status">Loading routines…</p> : null}{error ? <p role="alert" className={styles.error}>{error}<button onClick={() => void load()}>Retry</button></p> : null}{!loading && !error && !items.length ? <p className={styles.free}>No routines yet. Add a regular study time.</p> : null}{items.map(item => compact ? <article className={styles.routineMini} key={item.id}><div className={styles.routineMiniTitle}><Repeat2 size={15}/><h3>{item.message}</h3></div><p>{item.active ? 'Active' : 'Paused'} · {item.calendarPresentation === 'study_session' ? `${item.durationMinutes || 30} min study` : 'Scheduled activity'}</p><div className={styles.routineMiniActions}>{item.courseId ? <Button variant="outline" size="sm" onClick={() => onStart(item.courseId!, item.message)}>Start</Button> : null}<Button variant="ghost" size="sm" disabled={busy === item.id} onClick={() => void control(item, item.active ? 'pause' : 'resume')}>{item.active ? 'Pause' : 'Resume'}</Button><Button variant="ghost" size="sm" onClick={() => setEditing(item)}>Edit</Button></div></article> : <article className={styles.routineCard} key={item.id}><Repeat2 size={19}/><div><h3>{item.message}</h3><p>{item.active ? 'Active' : 'Paused'} · {item.calendarPresentation === 'study_session' ? `${item.durationMinutes || 30} minute study session` : 'Scheduled activity'} · {item.timezone}</p></div><div className={styles.controls}>{item.courseId ? <Button variant="outline" size="sm" onClick={() => onStart(item.courseId!, item.message)}>Start</Button> : null}<Button variant="outline" size="sm" disabled={busy === item.id} onClick={() => void control(item, item.active ? 'pause' : 'resume')}>{item.active ? 'Pause' : 'Resume'}</Button><Button variant="ghost" size="sm" onClick={() => setEditing(item)}>Edit</Button><Button variant="ghost" size="sm" disabled={busy === item.id} onClick={() => void control(item, 'delete')}>Delete</Button></div></article>)}{editing ? <RoutineForm key={editing === 'new' ? 'new' : editing.id} routine={editing === 'new' ? undefined : editing} calendars={calendars} courses={courses} zone={zone} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); window.dispatchEvent(new Event(CALENDAR_CHANGED)); }}/>:null}</div>;
}

function RoutineForm({ routine, calendars, courses, zone, onClose, onSaved }: { routine?: Routine; calendars: StudentCalendar[]; courses: CourseSummary[]; zone: string; onClose: () => void; onSaved: () => void }) {
  const [message, setMessage] = useState(routine?.message || ''), [timezone, setTimezone] = useState(routine?.timezone || zone), [course, setCourse] = useState(routine?.courseId || ''), [calendar, setCalendar] = useState(routine?.calendarId || calendars.find(c => c.source === 'local')?.id || '');
  const [presentation, setPresentation] = useState(routine?.calendarPresentation || 'study_session');
  const [duration, setDuration] = useState(routine?.durationMinutes || 30), [repeat, setRepeat] = useState(routine?.schedule.rrule || 'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR');
  const [start, setStart] = useState(() => `${dateKey(new Date(Date.now() + 86400000), timezone)}T18:00`), [endDate, setEndDate] = useState(''), [saving, setSaving] = useState(false), [error, setError] = useState('');
  const pending = useRef<{ hash: string; key: string } | null>(null);
  async function save() {
    setSaving(true); setError('');
    try {
      const startsAt = wallInstant(start, timezone);
      const schedule = routine?.schedule.type === 'cron' ? routine.schedule : { type: 'rrule', startsAt, rrule: repeat };
      const reminder = { message: message.trim(), timezone, schedule, courseId: course || null, calendarId: calendar || null, calendarPresentation: presentation, durationMinutes: duration, channels: routine?.channels || ['inbox'], actions: routine?.actions || [], sessionId: routine?.sessionId || null, buddyId: routine?.buddyId || null, condition: routine?.condition || null, maxFires: routine?.maxFires || 1000, expiresAt: endDate ? Date.parse(wallInstant(`${endDate}T23:59`, timezone)) / 1000 : routine?.expiresAt || null, quietStart: presentation === 'study_session' ? 0 : routine?.quietStart ?? 22, quietEnd: presentation === 'study_session' ? 0 : routine?.quietEnd ?? 8, catchupMinutes: routine?.catchupMinutes || 120 };
      const hash = JSON.stringify(reminder); if (pending.current?.hash !== hash) pending.current = { hash, key: crypto.randomUUID() };
      await request(routine ? `/v1/reminder-routines/${encodeURIComponent(routine.id)}` : '/v1/reminders', { method: routine ? 'PATCH' : 'POST', headers: { 'Idempotency-Key': pending.current.key }, body: JSON.stringify(routine ? { expectedRevision: routine.revision, action: 'edit', reminder } : reminder) }); onSaved();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save routine.'); }
    finally { setSaving(false); }
  }
  return <Dialog open onOpenChange={open => { if (!open && !saving) onClose(); }}><DialogContent className={styles.formDialog}><DialogHeader><DialogTitle>{routine ? 'Edit routine' : 'Add routine'}</DialogTitle><DialogDescription>A regular place in your week. Skip or pause it whenever you need.</DialogDescription></DialogHeader><form className={styles.form} onSubmit={e => { e.preventDefault(); void save(); }}>{error ? <p role="alert" className={styles.error}>{error}</p>:null}<label>Activity<input required value={message} onChange={e => setMessage(e.target.value)} placeholder="Review physics"/></label><label>Type<select value={presentation} onChange={e => setPresentation(e.target.value)}><option value="study_session">Reserve study time</option><option value="automation">Scheduled reminder or existing Buddy activity</option></select></label><label>Course<select value={course} onChange={e => setCourse(e.target.value)} disabled={!!routine}><option value="">No course</option>{courses.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Calendar<select value={calendar} onChange={e => setCalendar(e.target.value)}>{calendars.filter(c => c.source === 'local').map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{routine?.schedule.type !== 'cron' ? <><label>First session<input type="datetime-local" required value={start} onChange={e => setStart(e.target.value)}/></label><label>Repeat<select value={repeat} onChange={e => setRepeat(e.target.value)}><option value="FREQ=DAILY">Daily</option><option value="FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR">Weekdays</option><option value="FREQ=WEEKLY">Weekly</option>{!['FREQ=DAILY','FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR','FREQ=WEEKLY'].includes(repeat) ? <option value={repeat}>Existing custom recurrence</option> : null}</select></label></> : <p>The existing schedule will be preserved.</p>}<label>Duration in minutes<input type="number" min={5} max={480} value={duration} onChange={e => setDuration(Number(e.target.value))}/></label><label>Timezone<input required value={timezone} onChange={e => setTimezone(e.target.value)}/></label><label>End date (optional)<input type="date" value={endDate} onChange={e => setEndDate(e.target.value)}/></label><footer><Button type="button" variant="ghost" disabled={saving} onClick={onClose}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : 'Save routine'}</Button></footer></form></DialogContent></Dialog>;
}
