import {useEffect,useState} from 'react';
import {Text,TextInput,View,Switch,Pressable} from 'react-native';
import {api} from './account';
import {styles} from './theme';
import {FlashcardImage} from './FlashcardImage';
import type {Deck,FlashcardContent} from './flashcard-types';
export function NewFlashcard({deck,disabled,onSave}:{deck:Deck;disabled:boolean;onSave:(content:FlashcardContent)=>Promise<void>}){
 const [open,setOpen]=useState(false),[type,setType]=useState<FlashcardContent['type']>('qa'),[prompt,setPrompt]=useState(''),[answer,setAnswer]=useState(''),[quote,setQuote]=useState(''),[asset,setAsset]=useState(''),[alt,setAlt]=useState(''),[rights,setRights]=useState(false),[assets,setAssets]=useState<{versionId:string;title:string;mediaType:string}[]>([]),[mask,setMask]=useState({x:10,y:10,width:30,height:10}),[error,setError]=useState('');
 const visual=type==='image_label'||type==='image_occlusion';
 useEffect(()=>{if(!open||!visual)return;let active=true;void api.json<{materials:{versionId:string;title:string;mediaType:string}[]}>(`/v1/materials${deck.courseId?'?course_id='+encodeURIComponent(deck.courseId):''}`).then(value=>{if(active)setAssets(value.materials.filter(m=>['image/png','image/jpeg','image/webp'].includes(m.mediaType)))}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[open,visual,deck.courseId]);
 const image=visual?{versionId:asset,altText:alt,rightsConfirmed:rights,masks:type==='image_occlusion'?[{x:mask.x/100,y:mask.y/100,width:mask.width/100,height:mask.height/100}]:[]}:null;
 return <View style={styles.card}><Pressable accessibilityRole="button" onPress={()=>setOpen(v=>!v)}><Text style={styles.link}>Add a card</Text></Pressable>{open?<><View style={styles.row}>{(['qa','cloze','image_label','image_occlusion'] as const).map(value=><Pressable accessibilityRole="button" key={value} onPress={()=>setType(value)}><Text style={styles.link}>{type===value?'✓ ':''}{value.replaceAll('_',' ')}</Text></Pressable>)}</View><TextInput accessibilityLabel="New card prompt" multiline style={styles.input} placeholder="Prompt; cloze uses {{c1::answer}}" value={prompt} onChangeText={setPrompt}/><TextInput accessibilityLabel="New card answer" multiline style={styles.input} placeholder="Answer" value={answer} onChangeText={setAnswer}/><Text style={styles.muted}>Source: {deck.coverage.sources[0]?.title}</Text><TextInput accessibilityLabel="Supporting passage" multiline style={styles.input} placeholder="Supporting passage from this source" value={quote} onChangeText={setQuote}/>{visual?<>{assets.map(value=><Pressable accessibilityRole="button" key={value.versionId} onPress={()=>setAsset(value.versionId)}><Text style={styles.link}>{asset===value.versionId?'✓ ':''}{value.title}</Text></Pressable>)}{!assets.length?<Text style={styles.muted}>Upload an image under Materials first.</Text>:null}<TextInput accessibilityLabel="Alternative image description" style={styles.input} placeholder="Description without revealing the answer" value={alt} onChangeText={setAlt}/><Text style={styles.muted}>I have permission to use this image for my study cards</Text><Switch accessibilityLabel="Source-use permission confirmed" value={rights} onValueChange={setRights}/>{type==='image_occlusion'?<>{(['x','y','width','height'] as const).map(key=><View key={key}><Text style={styles.muted}>{key} (%)</Text><TextInput accessibilityLabel={`Mask ${key} percentage`} keyboardType="numeric" style={styles.input} value={String(mask[key])} onChangeText={value=>setMask(m=>({...m,[key]:Number(value)}))}/></View>)}</>:null}{asset&&alt?<FlashcardImage image={image}/>:null}</>:null}<Pressable accessibilityRole="button" disabled={disabled||!prompt||!answer||!quote||!deck.coverage.sources.length||visual&&(!asset||!alt||!rights)} onPress={()=>void onSave({type,prompt,answer,supportQuote:quote,explanation:'',sourceIds:[deck.coverage.sources[0].id],conceptIds:[],image}).then(()=>setOpen(false))}><Text style={styles.link}>Save draft card</Text></Pressable>{error?<Text style={styles.error}>{error}</Text>:null}</>:null}</View>;
}
