import {Flashcards} from './Flashcards';
import {account} from './account';
import {useEffect,useState} from 'react';
import {Text,View,Pressable,TextInput} from 'react-native';
import {WebView} from 'react-native-webview';
import * as Crypto from 'expo-crypto';
import {api} from './account';
import {download} from './files';
import type {Command,Decision} from './generated/api';
import {styles} from './theme';
import {Quiz} from './Quiz';
export type Task={deckId?:string;id:string;sessionId:string;revision:number;status:string;kind?:string;phase?:string;summary?:string;message?:string;allowedCommands?:string[];pendingRequests?:{requestId:string;revision:number;question:string;options:string[]}[];artifacts?:{id:string;name:string}[];sources?:{id:string;title:string}[];browserControl?:{owner:string;generation:string};connectionId?:string;completion?:{status:string}};
type Approval={account?:string;attachments?:unknown[];baseEvent?:unknown;id:string;revision:number;status:string;actionHash:string;preview?:{kind?:string;mail?:{to:string[];subject:string;body:string};event?:{summary:string;start:string;end:string}};mail?:{to:string[];subject:string;body:string};event?:{summary:string;start:string;end:string};kind?:string};
export function TaskCard({task,run,reply}:{task:Task;run:(action:()=>Promise<unknown>)=>void;reply:(task:Task,request:NonNullable<Task['pendingRequests']>[number],text:string)=>void}){
  const [answer,setAnswer]=useState(''),[excerpt,setExcerpt]=useState(''),[approvals,setApprovals]=useState<Approval[]>([]),[view,setView]=useState<{url:string;expiresAt:number;generation:string}|null>(null),[lesson,setLesson]=useState(''),[quizId,setQuizId]=useState<string|null>(null);
  useEffect(()=>{if(!view)return;const timer=setTimeout(()=>setView(null),Math.max(0,view.expiresAt*1000-Date.now()));return()=>clearTimeout(timer)},[view]);
  async function command(action:'pause'|'resume'|'cancel') {const body:Command={schemaVersion:2,commandId:Crypto.randomUUID(),action,expectedRevision:task.revision};await api.json(`/v1/assistant/tasks/${task.id}/commands`,{method:'POST',body:JSON.stringify(body)});}
  return <View style={styles.card}><Text style={styles.heading}>{task.message||'Task'}</Text><Text style={styles.muted}>{task.status} · {task.phase}</Text>{task.summary?<Text style={styles.text}>{task.summary}</Text>:null}
    <View style={styles.row}>{(['pause','resume','cancel'] as const).filter(action=>task.allowedCommands?.includes(action)).map(action=><Pressable accessibilityRole="button" key={action} style={styles.smallButton} onPress={()=>run(()=>command(action))}><Text style={styles.link}>{action==='cancel'?'Stop':action==='pause'?'Pause':'Resume'}</Text></Pressable>)}</View>
    {task.pendingRequests?.map(request=><View key={request.requestId}><Text style={styles.text}>{request.question}</Text>{request.options?.map(option=><Pressable accessibilityRole="button" key={option} onPress={()=>reply(task,request,option)}><Text style={styles.link}>{option}</Text></Pressable>)}<TextInput accessibilityLabel="Answer task question" style={styles.input} value={answer} onChangeText={setAnswer}/><Pressable accessibilityRole="button" onPress={()=>{if(answer.trim())reply(task,request,answer)}}><Text style={styles.link}>Send answer</Text></Pressable></View>)}
    {task.artifacts?.map(file=><Pressable accessibilityRole="button" key={file.id} onPress={()=>run(()=>download(file.id,file.name))}><Text style={styles.link}>↓ {file.name}</Text></Pressable>)}
    {task.sources?.map(source=><Pressable accessibilityRole="button" key={source.id} onPress={()=>run(async()=>{const result=await api.json<{excerpt?:string;title:string}>(`/v1/assistant/sources/${source.id}`);setExcerpt(result.excerpt||result.title)})}><Text style={styles.link}>{source.title}</Text></Pressable>)}{excerpt?<Text style={styles.text}>{excerpt}</Text>:null}
    {task.completion?.status==='verified'?<View style={styles.row}>{(['teach','quiz'] as const).map(kind=><Pressable accessibilityRole="button" key={kind} onPress={()=>run(async()=>{await api.json(`/v1/assistant/tasks/${task.id}/continuations`,{method:'POST',headers:{'Idempotency-Key':Crypto.randomUUID()},body:JSON.stringify({kind,expectedRevision:task.revision})});setLesson('Your '+(kind==='teach'?'explanation':'quiz')+' is being prepared.');})}><Text style={styles.link}>{kind==='teach'?'Explain this':'Practice quiz'}</Text></Pressable>)}<Pressable accessibilityRole="button" onPress={()=>run(async()=>{const result=await api.json<{items:{status:string;lesson?:{blocks:{body:string}[]} ;quizId?:string}[]}>(`/v1/assistant/tasks/${task.id}/continuations`);setQuizId(result.items.find(item=>item.quizId)?.quizId||null);setLesson(result.items.map(item=>item.lesson?.blocks?.map(b=>b.body).join('\n')||item.status).join('\n'));})}><Text style={styles.link}>View learning</Text></Pressable></View>:null}{lesson?<Text style={styles.text}>{lesson}</Text>:null}
    {task.kind && !task.connectionId?<Pressable accessibilityRole="button" onPress={()=>run(async()=>{const result=await api.json<{items:Approval[]}>(`/v1/assistant/tasks/${task.id}/actions`);setApprovals(result.items)})}><Text style={styles.link}>Review connected actions</Text></Pressable>:null}
    {approvals.map(action=>{const mail=action.mail||action.preview?.mail,event=action.event||action.preview?.event;return <View key={action.id}><Text style={styles.heading}>{action.kind||action.preview?.kind} · {action.status}</Text>{mail?<Text style={styles.text}>{mail.to.join(', ')}{'\n'}{mail.subject}{'\n'}{mail.body}</Text>:null}{event?<Text style={styles.text}>{event.summary}{'\n'}{event.start} → {event.end}</Text>:null}<Text style={styles.muted}>Account: {action.account||'See reviewed connection'}</Text><Text selectable style={styles.text}>{JSON.stringify({mail,event,attachments:action.attachments,previousEvent:action.baseEvent},null,2)}</Text>{action.status==='draft'?<View style={styles.row}>{(['approve','reject'] as const).map(decision=><Pressable accessibilityRole="button" key={decision} onPress={()=>run(async()=>{const body:Decision={decision,expectedRevision:action.revision,actionHash:action.actionHash};await api.json(`/v1/assistant/approvals/${action.id}/decision`,{method:'POST',headers:{'Idempotency-Key':Crypto.randomUUID()},body:JSON.stringify(body)});setApprovals([])})}><Text style={styles.link}>{decision==='approve'?'Approve this action':'Reject'}</Text></Pressable>)}</View>:null}</View>})}
    {task.connectionId?<View><Text style={styles.muted}>Browser: {task.browserControl?.owner||'agent'}</Text><Pressable accessibilityRole="button" onPress={()=>run(async()=>{setView(null);await api.json(`/v1/assistant/tasks/${task.id}/commands`,{method:'POST',body:JSON.stringify({action:task.browserControl?.owner==='human'?'return_control':'takeover',expectedRevision:task.revision})});})}><Text style={styles.link}>{task.browserControl?.owner==='human'?'Return browser control':'Take browser control'}</Text></Pressable>{task.browserControl?.owner==='human'?<Pressable accessibilityRole="button" onPress={()=>run(async()=>{const result=await api.json<{kind:string;url?:string;expiresAt?:number;generation:string;message?:string}>(`/v1/assistant/tasks/${task.id}/browser-view`);if(result.kind==='cloud' && result.url && result.expiresAt && result.generation===task.browserControl?.generation)setView({url:result.url,expiresAt:result.expiresAt,generation:result.generation});else setExcerpt(result.message||'Reconnect the paired desktop.')})}><Text style={styles.link}>Open private browser</Text></Pressable>:null}</View>:null}
    {view && task.browserControl?.owner==='human' && view.generation===task.browserControl.generation && view.expiresAt*1000>Date.now()?<WebView source={{uri:view.url}} style={{height:500}} javaScriptEnabled sharedCookiesEnabled={false} incognito onShouldStartLoadWithRequest={request=>request.url.startsWith('https://') || request.url==='about:blank'}/>:null}
    {task.deckId&&account()?.owner?<Flashcards owner={account()!.owner} sessionId={task.sessionId} initialDeckId={task.deckId}/>:null}
    {quizId?<Quiz id={quizId} run={run}/>:null}
  </View>;
}
