"use client";

import { useState } from 'react';
import {BuddyCustomization} from '@/components/buddy-customization';
import type {BuddyInput} from '@/lib/buddies';
import '@/components/buddies.css';
import Link from 'next/link';
import styles from './page.module.css';

import { Buddy, concepts, expressions, accessoryChoices, type Expression, type Accessory } from '@/components/buddy-character';
const colors = ['#B8CFA8', '#F0BA68', '#A9BDE2', '#E99381', '#BEA9DD'];

export default function BuddyDesign() {
  const [personal, setPersonal] = useState<BuddyInput>({name:'',avatar:'spark',color:'sage',style:'encouraging',concise:true,examples:true,proactive:false});
  const [selected, setSelected] = useState(0);
  const [color, setColor] = useState(colors[0]);
  const [expression, setExpression] = useState<Expression>('Neutral');
  const [light, setLight] = useState(false);
  const [animated, setAnimated] = useState(true);
  const [replay, setReplay] = useState(0);
  const [buddyName, setBuddyName] = useState('');
  const [accessories, setAccessories] = useState<Accessory[]>(['Beanie', 'Scarf']);
  return <main className={`${styles.board} ${light ? styles.light : ''}`}>
    <header className={styles.header}><Link href="/">← Open Learn</Link><span>CHARACTER STUDIES / 02</span><button onClick={() => setLight(!light)}>{light ? 'Dark canvas' : 'Light canvas'}</button></header>
    <section className={styles.intro}><p>A little presence. A lot of personality.</p><h1>Meet your next<br/>study companion.</h1><div>Eight shapes. Five ways to come alive. You choose the name, personality, and what your companion is best at. These labels describe the shapes only.</div></section>
    <section className={styles.personal}><div><p className={styles.eyebrow}>YOUR COMPANION</p><h2>A few choices. A Buddy of your own.</h2><p>Start with a name and a look. Open the extras only when you want them.</p><label className={styles.nameField}>Name<input maxLength={60} placeholder="What would you call your Buddy?" value={personal.name} onChange={event=>setPersonal({...personal,name:event.target.value})}/></label><p>Sleep follows your device’s local time. Try Sleepy, Sleeping, and Waking in the motion lab below, or leave this tab and return to see the greeting.</p><p>This is a preview. Save an actual companion through Customize Buddy in your chat.</p></div><BuddyCustomization value={personal} onChange={setPersonal}/></section>
    <details className={styles.lab}><summary>Explore the shapes & motion lab</summary>
    <section className={styles.concepts} aria-label="Choose a character direction">{concepts.map((concept, index) => <button key={concept.name} className={`${styles.concept} ${selected === index ? styles.selected : ''}`} aria-pressed={selected === index} onClick={() => { setSelected(index); setColor(concept.color); }}><span className={styles.number}>0{index + 1} / SHAPE</span><div className={styles.hero}><Buddy accessories={accessories} index={index} color={concept.color}/></div><h2>{concept.name}</h2><p>{concept.note}</p><div className={styles.sizes}><Buddy accessories={accessories} index={index} color={concept.color} size={32}/><Buddy accessories={accessories} index={index} color={concept.color} size={24}/><span>32px / 24px</span></div><span className={styles.choice}>{selected === index ? 'Selected direction' : 'Explore this direction'} →</span></button>)}</section>
    <section className={styles.studio}><div className={styles.controls}><p className={styles.eyebrow}>MAKE IT YOURS</p><h2>A little more alive.</h2><p>{({Neutral: "An easy breath, an occasional glance. Comfortable just being here.", Curious: "Leans closer, looks up, and pauses as if waiting for your answer.", Thinking: "A slow sway and an upward glance, with a pause to consider.", Happy: "A celebration unique to this shape: wind up, dance, tumble or twirl, then catch its breath.", Puzzled: "A double take, an uncertain wobble, and sometimes a sideways tumble before recovering.", Sleepy: "Heavy eyelids after a long study session or late in your local evening.", Sleeping: "Resting while you are away. Always ready to help.", Waking: "A stretch, a yawn, and a little hello when you return."})[expression]}</p><div className={styles.swatches} aria-label="Body color">{colors.map((value, index) => <button key={value} style={{ background: value }} aria-label={['Sage', 'Amber', 'Blue', 'Coral', 'Lavender'][index]} aria-pressed={color === value} onClick={() => setColor(value)}/>)}</div><div className={styles.expressionButtons}>{expressions.map(value => <button key={value} aria-pressed={expression === value} onClick={() => setExpression(value)}>{value}</button>)}</div><div className={styles.wardrobe}><p className={styles.eyebrow}>LITTLE EXTRAS · MIX & MATCH</p><div className={styles.expressionButtons}>{accessoryChoices.map(item => <button key={item} aria-pressed={accessories.includes(item)} onClick={() => setAccessories(current => current.includes(item) ? current.filter(value => value !== item) : [...current.filter(value => !(['Cap', 'Beanie'].includes(item) && ['Cap', 'Beanie'].includes(value))), item])}>{item}</button>)}<button onClick={() => setAccessories([])} disabled={!accessories.length}>Clear</button></div><p>Choose a beanie or cap, then mix in the other extras. The cap’s brim bounces as your Buddy moves.</p></div><label className={styles.motion}><input type="checkbox" checked={animated} onChange={event => setAnimated(event.target.checked)}/> Animate expressions</label></div><div className={styles.stage}><Buddy accessories={accessories} key={`${selected}-${expression}-${replay}`} index={selected} color={color} expression={expression} size={220} animated={animated}/><span aria-live="polite">{expression} · {(["Roll & rebound", "Somersault", "Corner tumble", "Petal twirl", "Spring & flip", "Float & flutter", "Heel-to-toe dance", "Pinwheel"])[selected]}</span><button className={styles.replay} onClick={() => setReplay(value => value + 1)}>↻ Replay motion</button></div></section>
    <section className={styles.expressionStrip} aria-label="Expression studies">{expressions.map(value => <div key={value}><Buddy accessories={accessories} index={selected} color={color} expression={value} size={80} animated={animated}/><span>{value}</span></div>)}</section>
    <section className={styles.context}><div><p className={styles.eyebrow}>IN YOUR WORKSPACE</p><h2>The character is yours.</h2><p>A shape doesn’t decide a personality. Any of these can be your patient math coach, your playful writing partner, or something entirely your own.</p><label className={styles.nameField}>Try a name<input value={buddyName} onChange={event => setBuddyName(event.target.value)} maxLength={40} placeholder="Your companion’s name"/></label><p className={styles.previewNote}>Design preview only · naming here does not create a Buddy.</p></div><div className={styles.mock}><aside><span>⌂</span><span>⌕</span><button aria-label="Selected Buddy"><Buddy accessories={accessories} index={selected} color={color} size={32}/></button><span>＋</span></aside><div><header><Buddy accessories={accessories} index={selected} color={color} size={24}/><strong>{buddyName.trim() || 'Your Buddy'}</strong><span>⌄</span></header><p className={styles.mockQuestion}>Why does a heavier object need more force?</p><div className={styles.reply}><Buddy accessories={accessories} index={selected} color={color} expression="Curious" size={36}/><p>Let’s start with something you can feel. Imagine pushing an empty shopping cart, then one filled with books.</p></div><div className={styles.input}>Ask a follow-up… <span>↑</span></div></div></div></section>
    </details>
    <footer className={styles.footer}>Open Learn · Buddy visual exploration <span>Flat color. Clear silhouette. A face worth knowing.</span></footer>
  </main>;
}

